[profile.default]
# solc-version = '0.8.22'
auto_detect_solc = true
optimizer = true
optimizer_runs = 150
src = 'contracts'
out = 'out'
test = 'test'
cache_path = 'cache'
verbosity = 1
show_progress = true

# Enable traces for better error messages
traces = true

remappings = [
    '@balancer-labs/v3-interfaces/=lib/balancer-v3-monorepo/pkg/interfaces/',
    '@balancer-labs/v3-pool-utils/=lib/balancer-v3-monorepo/pkg/pool-utils/',
    '@balancer-labs/v3-solidity-utils/=lib/balancer-v3-monorepo/pkg/solidity-utils/',
    '@balancer-labs/v3-vault/=lib/balancer-v3-monorepo/pkg/vault/',
]
fs_permissions = [{ access = "read-write", path = "./"}]

[fmt]
line_length = 100
